### PR TITLE
[1.x] Improve Excel workbook processing and logging

### LINKED ISSUE #28: NoSuchMethodException: org.apache.logging.log4j.message.ReusableMessageFactory
When you have a sheet and you enable the following:

  wb.getCreationHelper().createFormulaEvaluator().evaluateAll();

Then you will get a the following error:

` "exception": {
                        "refId": 3,
                        "exceptionType": "java.lang.NoSuchMethodException",
                        "message": "org.apache.logging.log4j.message.ReusableMessageFactory.<init>()",
                        "frames": [
                            {
                                "class": "java.lang.Class",
                                "method": "getConstructor0",
                                "line": 3585
                            },
                            {
                                "class": "java.lang.Class",
                                "method": "newInstance",
                                "line": 626
                            },
                            {
                                "class": "org.apache.logging.log4j.spi.AbstractLogger",
                                "method": "createDefaultMessageFactory",
                                "line": 228
                            },
                            {
                                "class": "org.apache.logging.log4j.spi.AbstractLogger",
                                "method": "<init>",
                                "line": 143
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLogger",
                                "method": "<init>",
                                "line": 48
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLoggerContext",
                                "method": "getLogger",
                                "line": 72
                            },
                            {
                                "class": "org.jboss.logmanager.log4j.JBossLoggerContext",
                                "method": "getLogger",
                                "line": 62
                            },
                            {
                                "class": "org.apache.logging.log4j.LogManager",
                                "method": "getLogger",
                                "line": 666
                            },
                            {
                                "class": "org.apache.poi.ss.formula.WorkbookEvaluator",
                                "method": "<init>",
                                "line": 81
                            },
                            {
                                "class": "org.apache.poi.ss.formula.WorkbookEvaluator",
                                "method": "<init>",
                                "line": 89
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator",
                                "method": "<init>",
                                "line": 41
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator",
                                "method": "<init>",
                                "line": 38
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFCreationHelper",
                                "method": "createFormulaEvaluator",
                                "line": 84
                            },
                            {
                                "class": "org.apache.poi.xssf.usermodel.XSSFCreationHelper",
                                "method": "createFormulaEvaluator",
                                "line": 32
                            },`

I think the fix is something like this for me. But could you also support this in your plugin?
```
[
  {
    "name": "org.apache.logging.log4j.message.ReusableMessageFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "org.apache.logging.log4j.message.DefaultFlowMessageFactory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]
```

Seems like the same issue : https://github.com/quarkusio/quarkus/issues/13575

### PR DESCRIPTION
**Pull request by gastaldi**
- Add formula evaluation to Excel workbook
- Add a `registerLog4jClassesForReflection` BuildStep to register 3 Log4j classes for reflection
- Fixes #28

### CODE REVIEW

File: deployment/src/main/java/io/quarkiverse/poi/deployment/POIProcessor.java [hunk 1]
```diff
@@ -58,4 +58,13 @@ void registerXMLBeansClassesForReflection(CombinedIndexBuildItem combinedIndexBu
...
         }
     }
+
+    @BuildStep
+    public ReflectiveClassBuildItem registerLog4jClassesForReflection() {
+        return new ReflectiveClassBuildItem(true, true,
+                "org.apache.logging.log4j.message.ReusableMessageFactory",
+                "org.apache.logging.log4j.message.DefaultFlowMessageFactory",
+                "org.apache.logging.log4j.message.ParameterizedMessageFactory");
+    }
```
Comment (gsmet) [inline deployment/src/main/java/io/quarkiverse/poi/deployment/POIProcessor.java:68]: For my understanding, are they from the API? Because you're not supposes to use the Log4j2 implementation so I'm surprised you need to add reflection there.
